### PR TITLE
feat(variables): support service-specific pipeline variables. fixes #686

### LINKED ISSUE #686: Support service for pipeline variables/secrets
**Expected Behaviour**

The pipeline variable API now supports service for pipeline variables and that should be available in the CLI.

### PR DESCRIPTION
**Pull request by sii41383**
## Description

Supports service for pipeline variables was added in the CLI.

## Related Issue

#686

## Motivation and Context

The pipeline variable API now supports service for pipeline variables and that should be available in the CLI.

## How Has This Been Tested?

Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by proactivebit** [comment]
Code and test ok

**Review by proactivebit — DISMISSED** [review]

**Comment by proactivebit** [comment]
To change:
- Change in readme min required node version to 16,
- Set version to 4.2.0,
- Add changelog info

**Comment by anastasiapintilie** [comment]
I have not tested, but codewise i don't notice anything off. Why was the node version update needed?

**Comment by proactivebit** [comment]
> I have not tested, but codewise i don't notice anything off. Why was the node version update needed?

Dependencies has changed and they are using now code from javascript 16. In other case we will get error when doing npm test as shown bellow.
image

**Review by anastasiapintilie — APPROVED** [review]

**Comment by kwin** [comment]
The readme requires some updates still. The authentication paragraph still only documents the JWT based one.

**Pull request merged**
