### PR TITLE
feat(commerce-base-command): commerce fixes #487

### LINKED ISSUE #487: Add Commerce tail log functionality to commerce base command
**Is your feature request related to a problem? Please describe.**

We need to commerce tail log functionality to commerce base command, so that when we call a commerce command, the relevant logs are shown to the user. 

**Describe the solution you'd like**

I would prefer this tail log functionality added to the commerce base command instead of each individual commerce command. 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by rwalter215**
Added tail log functionality to the commerce base command, updated unit tests
## Description

* Added tail log functionality to the commerce base command 
* updated unit tests
* removed `cli.start` and `cli.stop` and replaced with logging to match mocks

## Motivation and Context

Fixes issue #487

## How Has This Been Tested?
manual and unit testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rwalter215** [comment]
Since I am logging instead of using `cli.start` and `cli.stop`, that the output of my unit tests is messy. Is there a preferred way for me to mock `this.log` and `this.warn` ? The oclif docs say to use https://github.com/jdxcode/stdout-stderr

**Comment by justinedelson** [comment]
> Since I am logging instead of using cli.start and cli.stop, that the output of my unit tests is messy. Is there a preferred way for me to mock this.log and this.warn ? The oclif docs say to use https://github.com/jdxcode/stdout-stderr

@rwalter215 I've found stderr-stdout to be kind of a pain. I was actually thinking about this yesterday and I think https://github.com/adobe/aio-cli-plugin-cloudmanager/pull/491 is a reasonable solution. 

Question for you: do you want me to merge that first and then you can adjust your changes to take advantage of the mocked info (i.e. make assertions on it)? Or merge this first and then that?

**Comment by rwalter215** [comment]
I'm cool with either. But maybe merge this PR first, and then we can look at PR #490 while I update the unit tests.

**Comment by justinedelson** [comment]
491 was merged

**Comment by rwalter215** [comment]
Cool, this PR should be good to go. Thanks for doing all of that work regarding the unit tests. Saved me a bunch of time. I just had to change `info` to `log` and was good to go.

**Pull request merged**
